---
title: New Outline for Chapter 3
subtitle: Atlantic Bluefin Tuna Area Transition Matrices Estimated From Electronic Tagging and SatTagSim
authors:
  - name: Benjamin Galuardi
    affiliation: School of Marine Science and Technology, University of Massachusetts Dartmouth, Fairhaven, MA, USA
    roles: writing, analysis
    corresponding: true
    email: benjamin.galuardi@noaa.gov
  - name: Steven X. Cadrin
    affiliation: School of Marine Science and Technology, University of Massachusetts Dartmouth, Fairhaven, MA, USA
    roles: writing
  - name: Igor Arregi
    affiliation: AZTI Technalia, Marine Research Division, Pasaia (Gipuzkoa), Spain
    roles: writing
  - name: Haritz Arrizabalaga
    affiliation: AZTI Technalia, Marine Research Division, Pasaia (Gipuzkoa), Spain 
    roles: data and analysis
  - name: Antonio DiNatale
    affiliation: ICCAT Secretariat, Madrid, Spain
    roles: data and analysis
  - name: Craig Brown
    affiliation: Southeast Fisheries Science Center, NOAA Fisheries, Miami, FL, USA
    roles: data and analysis
  - name: Matt Lauretta
    affiliation: Southeast Fisheries Science Center, NOAA Fisheries, Miami, FL, USA
    roles: data and analysis
  - name: Molly Lutcavage
    affiliation: Large Pelagics Research Center, Gloucester, MA, USA     
    roles: writing, data, and analysis
bibliography: references.bib
format:
  elsevier-pdf:
    journal:
      name: "Fisheries Research"
      formatting: preprint
      model: 5p
      layout: onecolumn
      cite-style: authoryear
      highlights:
    include-in-header: 
      text: |
        \newpageafter{author}
  html: default
  docx: default
  jats: default
  plos-pdf: default
---

# Summary (2017 SCRS)

We demonstrate use of a telemetry based method for simulating individual based movements to produce transition matrices for movement inclusive models. A custom R package (SatTagSim) was used on Atlantic bluefin tuna electronic tagging data from the Large Pelagics Research Center (UMass Boston), AZTI Technalia, the Grande Bluefin Year Program, and the National Marine Fisheries Service (USA) to derive transition matrices for an 11-box and 4-box model. Migration rate matrices were produced for western Atlantic tagged fish \>185cm, and \<185 cm, as well as for eastern tagged fish (all sizes). The estimates provided are fishery independent and external to the operational and assessment frameworks. The results are highly informative to the assessment by (1) providing estimates of bluefin tuna movement for consideration as fixed values, prior probabilities on movement, or for direct comparison with estimates of movement from mixed stock assessment models (2) to facilitate discussion of movement rate assumptions and the use of electronic tagging data in various assessment models.

# Introduction (2017 SCRS)

The benchmark assessment of Atlantic Bluefin tuna (*Thunnus thynnus*) in 2017 offers a unique opportunity to take advantage of the wealth of electronic tagging data collected in the past 20+ years. <!--# this is old news. this should be updated -->The Grande Bluefin Year Program (GBYP), a project within the International Commission for the Conservation of Atlantic Tunas (ICCAT), in particular offers a source of tagging data originating in the eastern Atlantic that was not previously available. Management strategy evaluation (MSE) is a priority for Atlantic bluefin tuna management and is currently a funded initiative within ICCAT [@carruthers2014]. Development of operating models is a key component to MSE and can be a vector for utilizing electronic tag data [@kerr2012a; @kerr2016; @carruthers2016]

There are several challenges in making these data usable in assessment activities. The first is to summarize the data in a way that is readily usable by models. Not all tagging data are equal in terms of length, area, and season of deployment. Fish are often tagged opportunistically, when and where they are accessible e.g. [@galuardi2012, @cermeño2015, @wilson2015]. Last, tagging data are expensive to collect and hold incredibly high scientific value. Allowing time for individual programs to publish results often means data are not quickly available for other purposes.

The solution to many of these issues is to simplify the manner in which the data are represented, and summarize it in an easily usable format. Empirical summaries by area and season offer the simplest method for incorporating many different data sources without compromising individuals information for other purposes [@carruthers2016a]. Simple summaries do not, however, take into account the uncertainties in the positions from which they were derived and do not deal effectively with the biases of short tracks in these datasets. A more robust method is to use individual based simulation, based on the tagging data, to produce movement probability metrics by season and area [@galuardi2014]. Here, we use several electronic tagging datasets, from the eastern and western Atlantic (Figure 1), to produce seasonal movement matrices for use in current and future operational and assessment models of Atlantic bluefin tuna. We use the 11-box model developed for the GBYP MSE [@carruthers2016a] as well as a simplified 4-box model. Simulation and matrix derivations were carried out using a custom package (SatTagSim) for the R statistical software [@rcoreteam2024].

# intro to SCRS 2014 paper

Atlantic bluefin tuna are managed as separate eastern and western stocks (ICCAT 2022), but tagging data, genetic, stable isotope and chemical tracer studies suggest that potentially significant mixing exists between these stocks (CITE a bunch of papers here..). Failing to account for this mixing could lead to a biased view of stock status and have significant ramifications on the management of the species.

Modeling efforts by managers and researchers have attempted to account for mixing in various ways. Porch (2003) developed the 2-box VPA model, which allows for movement between stocks, and is the current model used by ICCAT to assess the two stocks. The most recent assessment did not, however, include mixing as an input (ICCAT 2022). A fully integrated, multi-stock statistical catch at age model (MAST) was developed by Taylor et al. (2011) and was built to include conventional and electronic tagging data as well as isotopically assigned natal origin information. The model had convergence issues and difficulty estimating confounded movement parameters, but highlighted areas in which assessment of bluefin tuna (and other species) could be improved.

Management strategy evaluation (MSE) was pursued by as a management priority for Atlantic bluefin tuna (ICCAT Workshop on Stock Assessment Methods, July, 2014, Carruthers many refs.., Cadrin, Morse, Kerr). A key component of MSE is use of an operational model.

Kerr et al. (2012) developed an operational model, based on the MAST framework, that simulates spawning stock biomass in a spatially explicit fashion under differing assumptions of fishing mortality and other parameters.

Movement parameterization was in the form of Markovian state transition matrices where portions of the population moved seasonally between a set of areas (states).

Kerr at al.’s (2012) model used movements estimated from MAST, using both bulk transfer and gravity based estimates as alternative operating models for simulation. 

Each of these estimation methods has drawbacks: Bulk transfer, in which all off-diagonal matrix cells (i.e., transfer coefficients from one area to another) are estimated, made convergence difficult for MAST while the gravity method, in which an ‘attraction’ coefficient is estimated for each area to derive residence, and movement is derived from relative attraction of other areas in that season, is not realistic.    

### add this to chapter 2 if it fits..

> Empirical information from tagging studies has often been cited as being useful towards stock assessment, and the efforts to date have been split among two camps: Those that seek to use electronic tag data for mortality and/or movement estimation (Miller and Andersen 2008, Eveson et al. 2012, Whitlock et al. 2012) and those designed to scale individual movements to population levels (Sibert et al. 1999, 2006, Sibert and Fournier 2001). In particular, Sibert (2006) showed that advection diffusion population simulations, based on the movement of groups of tagged individuals, may be used to compare distribution in different time periods.
>
> We developed a telemetry based simulation method to parameterize movement in a biologically realistic manner, and to alleviate estimating problems encountered using MAST or the potential biases involved in estimating movement from fishery recaptures of conventional tags. We draw upon a large database of movement information from electronically tagged Atlantic bluefin tuna and introduce a framework which may be used to examine mixing between eastern and western Atlantic bluefin tuna stocks, be input directly into operational and spatially explicit assessment models, and be broadly applicable to other electronic tagging studies and spatial strata.

## elements/sections

Di Natale, Antonio Director, Aquastudio Research Institute, Via Trapani 6, 98121 Messina, Italy Tel: +39 336 333 366, E-Mail: adinatale\@costaedutainment.it; adinatale\@acquariodigenova.it

The best idea is to make the AFS 2017 talk into a chapter. It has all the elements it just need text. Basic textr can be used from the SCRS 2017 paper but the matrices, pieces, and interpretations are beyond what that paper offered.

-   Was mixing considered in the most recent assessment? It does not appear so..

    -   VPA used and [SS3 adopted]{.underline}

    -   ASAP model considered? SCRS paper

        -   Carrano, C., Maguire, J.-J., Kerr, L., Walter, J., Lauretta, M., Rouyer, T., and Cadrin, S. X. 2022. 2022 ASAP STOCK ASSESSMENT OF THE EASTERN ATLANTIC AND MEDITERRANEAN BLUEFIN TUNA. Collect. Vol. Sci. Pap. ICCAT **79**(3): 551–586.

-   update SCRS 2017 paper with figures/text from using 3D parameters

    -   This was already done for the AFS 2017 talk!!
    -   Use these figures: "C:\\Users\\ben\Google Drive\\PHD\\PUBS_TALKS\\AFS2017\\FIGS"
    -   Use this script! "C:\\Users\\ben\\Google Drive\\PHD\\COLLABORATIONS\\AFS_2017_figs_8-8-17.r"

-   How many tracks were used?

    -   SRCS 2017 499 fish

        -   113 (\<185 CFL, west)

        -   189 (\>185 CFL, west)

        -   166 (Eastern tagged fish)

    -   AFS: 170 east, 220 west E/W size split?

        -   West fish were large ones only and had \>=21 days/track

        -   Looks like 245 large fish were used for AFS... PPT says 220 but dataset shows 245

            -   190-301 cm CFL

            -   LPRC: 7 archival, 149 MTI, 33 WC

            -   DAL 23-655

            -   2002-2016

        -   East fish had a few added between SCRS and AFS

        -   how was variance derived?

            -   use lots of sims where nreps is a run; do median and compute 95% quantiles (2.5-97.5)

        -   what was left out between SCRS and AFS?? smaller fish?

<!-- -->

-   Add E/W combination

    -   AFS: 170 east, 220 west E/W size split

        -   I did this previoslyl but didn't use the results for anything.

            -   120,000 simulated fish, 4 positions/month, two year tracks

            -   1200 fish, 100 reps. Each rep has different starting points

            -   shared parameters between east and west fish, simply combine all tracks and generate movement parameters as a single set. Western regions will be more heavily influenced by western tagged fish and vice versa, but since each groups has some crossover, there is sharing of movement information

            -   

                -   demonstrates sharing of movement parameters in the case of mixing
                -   takes 5.5 minutes on lenovo laptop (Ryzen7).. probably way faster on server..

-   use $\chi^2$ goodness of fit to compare transitions between small/large fish

    -   multinomial variance

    -   use matrix variance example

-   use $\chi^2$ goodness of fit to compare transitions between E/W

## Chapter 2 notes

intro from 2014 SCRS paper holds some additional text that could be valuable

-   add visual of advection calculation
-   add method/demo of variance calculation
-   add method/demo of overall transition rate
-   add method/demo of comparison between two matrices
-   add functions to do comparisons
