---
title: quarto_ms
authors:
  - name: Benjamin Galuardi
    affiliation: School of Marine Science and Technology, University of Massachusetts Dartmouth, Fairhaven, MA, USA, bgaluardi@umassd.edu
    roles: writing, analysis
  - name: Steven X. Cadrin
    affiliation: School of Marine Science and Technology, University of Massachusetts Dartmouth, Fairhaven, MA, USA
    roles: writing
  - name: Igor Arregi
    affiliation: AZTI Technalia, Marine Research division, Pasaia (Gipuzkoa), Spain
    roles: writing
  - name: Haritz Arrizabalaga
    affiliation: AZTI Technalia, Marine Research division, Pasaia (Gipuzkoa), Spain 
    roles: data and aanalysis
    corresponding: true
  - name: Antonio DiNatale
    affiliation: ICCAT Secretariat, Madrid, Spain
    roles: data and aanalysis
  - name: Craig Brown
    affiliation: Southeast Fisheries Science Center, NOAA Fisheries, Miami, FL, USA
    roles: data and aanalysis
  - name: Matt Lauretta
    affiliation: Southeast Fisheries Science Center, NOAA Fisheries, Miami, FL, USA
    roles: data and aanalysis
  - name: Molly Lutcavage
    affiliation: Large Pelagics Research Center, Gloucester, MA, USA     
    roles: writing, data, and aanalysis
bibliography: references.bib
---

# Summary

We demonstrate use of a telemetry based method for simulating individual based movements to produce transition matrices for movement inclusive models. A custom R package (SatTagSim) was used on Atlantic bluefin tuna electronic tagging data from the Large Pelagics Research Center (UMass Boston), AZTI Technalia, the Grande Bluefin Year Program, and the National Marine Fisheries Service (USA) to derive transition matrices for an 11-box and 4-box model. Migration rate matrices were produced for western Atlantic tagged fish \>185cm, and \<185 cm, as well as for eastern tagged fish (all sizes). The estimates provided are fishery independent and external to the operational and assessment frameworks. The results are highly informative to the assessment by (1) providing estimates of bluefin tuna movement for consideration as fixed values, prior probabilities on movement, or for direct comparison with estimates of movement from mixed stock assessment models (2) to facilitate discussion of movement rate assumptions and the use of electronic tagging data in various assessment models.

Keywords: bluefin tuna, movement, stock assessment, electronic tags,

# Introduction

The benchmark assessment of Atlantic Bluefin tuna (Thunnus thynnus) in 2017 offers a unique opportunity to take advantage of the wealth of electronic tagging data collected in the past 20+ years. The Grande Bluefin Year Program (GBYP), a project within the International Commission for the Conservation of Atlantic Tunas (ICCAT), in particular offers a source of tagging data originating in the eastern Atlantic that was not previously available. Management strategy evaluation (MSE) is a priority for Atlantic bluefin tuna management and is currently a funded initiative within ICCAT [@carruthers2014]. Development of operating models is a key component to MSE and can be a vector for utilizing electronic tag data [@kerr2016](Kerr et al., 2012, 2016; Carruthers et al., 2016a).

There are several challenges in making these data usable in assessment activities. The first is to summarize the data in a way that is readily usable by models. Not all tagging data are equal in terms of length, area, and season of deployment. Fish are often tagged opportunistically, when and where they are accessible (e.g. Galuardi and Lutcavage 2012, Cermeño et al. 2015, Wilson et al. 2015). Electronic tags consist of implantable and pop-up satellite tags from several manufacturers, each with specific methods of deriving positional information. The quality of the positions is poor, and requires statistical or algorithmic correction to derive reasonable geolocation estimates (Teo et al. 2004, Lam et al. 2010a, Galuardi and Chi Hin (Tim) 2014, Neilson et al. 2014). Last, tagging data are expensive to collect and hold incredibly high scientific value. Allowing time for individual programs to publish results often means data are not quickly available for other purposes.

The solution to many of these issues is to simplify the manner in which the data are represented, and summarize it in an easily usable format. Empirical summaries by area and season offer the simplest method for incorporating many different data sources without compromising individuals information for other purposes (Carruthers et al., 2016b). Simple summaries do not, however, take into account the uncertainties in the positions from which they were derived and do not deal effectively with the biases of short tracks in these datasets. A more robust method is to use individual based simulation, based on the tagging data, to produce movement probability metrics by season and area (Galuardi et al., 2014). Here, we use several electronic tagging datasets, from the eastern and western Atlantic (Figure 1), to produce seasonal movement matrices for use in current and future operational and assessment models of Atlantic bluefin tuna. We use the 11-box model developed for the GBYP MSE (Carruthers et al., 2016b) as well as a simplified 4-box model. Simulation and matrix derivations were carried out using a custom package (SatTagSim) for the R statistical software (R Core Team 2015).

# Methods

To generate movement probability matrices, we used methods modified and updated from Galuardi et al. (2014). Tagging data were available from several sources including the Large Pelagics Research Center of the University of Massachusetts Boston, AZTI Technalia, the GBYP and the NOAA Southeast Fisheries Science Center (Table 1). We used a total of 499 tagged fish ranging from 66 to over 300 cm curved fork length (CFL). These data were split into eastern and western areas releases, defined by the 45o W Longitudinal stock boundary. Western tagged fish were further split into categories \>= 185cm CFL (n = 189) and \< 185cm CFL (n = 113), for a total of three groups. The size split in the western Atlantic is consistent with the commercial size limit of the United States and represents an approximately 7-8 year old fish (Restrepo et al., 2010). Fish tagged in the eastern Atlantic (n = 166) were often tagged underwater and were not measured consistently. Therefore, this group could not be reliably divided by size/age. We recognize there are several additional institutions, with substantial electronic tagging data, which were not included in this study due to availability at the time of the work. For each group of tagged fish, monthly advection parameters (u and v, mean and standard deviation) were calculated from the final estimated tracks for the group for that month. Diffusive parameters (D, mean and standard deviation) were calculated using either the diffusion parameter estimated from a Kalman filter state space model, or the fixed values used in the estimation. Fixing a diffusion parameter often occurs when using the KFtrack family of estimation models (e.g. Sibert et al. 2003, Lam et al. 2010b), and is standard practice for CLS derived tracks. These parameters were used in a correlated random simulation scheme that is parameterized in terms of the advective and diffusive parameters (Sibert et al., 2003, 2006; Galuardi et al., 2014).

For each group, 84 fish were ‘released’ each month (1,008/year). Starting points were determined by mapping the density of observations each month, and randomly selecting 1o grid cells in proportion to the densities. In this manner, simulations were started in all months and in all areas where observations took place, while retaining the relative importance of the observations. Each track was simulated for 720 days (\~ 2 years), with daily positions being derived by sampling the parameters in the previous step, and generating steps or a correlated random walk (Galuardi et al., 2014). A sea surface temperature climatology (Boyer et al., 2013) was used to keep simulated fish both in the water and in suitable water masses. Suitable temperature was determined by determining the 95% intervals of tag measured temperatures from the LPRC dataset for each month (Figure 2). Sea surface temperature can show considerable inter-annual variability which could affect habitat suitability for a particular year. However, since we combined tagging data from all years, a climatology was both more appropriate and more practical for the simulation framework. ETOPO1 bathymetric data (Amante and Eakins, 2009) were combined with the World Ocean Atlas 1o surface temperatures for each month to represent habitat available for simulated fish. The bathymetry layer was modified to reduce barrier effects of Florida, the Straits of Gibraltar and through the Laurentian Channel. The tag measured temperature limits were applied to these layers for each month, and temperatures out of range were clipped. A moving time window was used as a further selection criterion so that for a given location, at least two months out of a three month window had to meet the temperature range criteria. This step was intended to keep simulated fish out of the sub-arctic water in winter and out of tropical water in the summer.

Simulated fish were assigned to an area occupied each day through a geoprocessing overlay step. Both an 11-box and 4 box model were considered (Figure 3). To determine occupancy and transition, the first box occupied in each season was selected as the box occupied that season. Seasonal transition probabilities were then calculated by cross-tabulating the previous and currently assigned box for each fish for each season and dividing by the total for each row. For rows where no simulated fish occurred, a value of 1 was inserted in the diagonal position for that row (i.e. no movement from that area between seasons). This preserves the matrices Markovian properties where the row-wise probabilities must sum to 1.

To determine the mean and variance of each transition, the described simulation was repeated 1000 times, for a total of 1,008,000 simulated fish in each group. A 95% confidence interval was approximated for each matrix cell by calculating the 2.5% and 97.5% quantiles. The simulations were done in parallel using a desktop computer with an 8-core Intel i7 3.4GHz processor. Each group run took \~18 hours to complete. In prior efforts, without the replication for variance, runs of 12,000 simulated fish took 15-20 minutes on a standard laptop running 4 cores in parallel.

# Results

A total of six movement probability matrices were constructed for the three groups and two spatial structures (Figures 4-9). Values in each cell represent the mean and 95% confidence intervals for the 1000 runs. Cells where the confidence interval was extremely small are indicative of either very low occurrences in that season/area, or., that there were no movements to those, or a combination of these. Figures 6 and 9 demonstrates this for region 1 (the Gulf of Mexico), for fish tagged in the eastern Atlantic, and Figures 4, 5, 7 and 8 show similar results for simulations from western tagged fish in Mediterranean boxes. Parameters derived from the tagging data and used for the simulations are found in Tables 2-4.

# Discussion

Spatially explicit and operational and assessment models require use of some form of movement matrix to either to assign or estimate probability of movement between areas of interest. Using a simulation framework (SatTagSim) has several advantages: 1) producing these matrices external to the modeling framework should improve computational performance by reducing the confounding between movement and mortality parameter estimates within mixed stock models 2) use of simulations, instead of empirical summaries, acts as a form of bootstrap and extends the utility of the information available 3) summarizing movement parameters across time allows the use of any spatial stratification. In the case of Atlantic Bluefin tuna, these could be across stock boundaries, spawning regions, and among fishery reporting regions. Finally, use of electronic tagging data provides fishery independent estimates of fish movements.

This work is an updated version of work presented at the 2016 bluefin data preparation meeting, and follows the preliminary work in Galuardi et al. (2014). Several caveats should be kept in mind with respect to this method. First, the simulation method does not constrain fish to any specific area. This is a fundamentally different decision than what was used in MAST model (Taylor et al., 2011), where fish in certain regions were not allowed to transit to other regions (e.g. the Gulf of St. Lawrence to the Mediterranean). SatTagSim only constrains movement according to the movement parameters derived from tagging data and subsequent track estimation. This has the advantage of freely allowing for stochasticity in the simulation according to the data. Second, the temperature constraints are biologically reasonable but are somewhat subjective in application. SatTagSim allows the user to specify, within the moving time window, the number of suitable months for surface temperature (1 – 3 months). This was included in the method to keep fish out of areas that are typically beyond their thermal range, but can also act as a barrier if, for example, the temperature climatology changes quickly from one month to the next. The level of temporal detail in the World Ocean Atlas allows only for a monthly time step. A more continuous climatology may be worth consideration.

The most useful consideration in using tagging within a mixed stock assessment is knowledge of the stock of origin of the tagged fish. Determining stock of origin from tagging data is not easily accomplished since many assumptions must be made about spawning site fidelity, spawning frequency, maturity, condition, spawning area, etc. Furthermore, the prevalence of short tracks (Figure 10) disallows many of these tracks from consideration since they were not at liberty long enough even to apply these assumptions. Therefore, we did not make assumptions of stock origin in this work and classified fish based only according to where they were tagged. Given current knowledge of mixing rates from otolith work (e.g. Rooker et al., 2014, Siskey et al., 2016), it is reasonable to assume a majority of our fish tagged originated from the stock primarily associated with the tagging region. A detailed breakdown of size, location and season of tagged fish would be necessary to have a better understanding of possible stock origin of tagged fish.

Future work should include simulations and movement matrices using only fish that visited a known spawning area. The simplest version of this could be assigning western stock origin to tagged fish that visited the Gulf of Mexico and eastern origins to fish that visited, or were tagged in, the Mediterranean. Recent work highlighting the prevalence of spawning in the Slope Sea in the western Atlantic (Richardson et al., 2016) could add additional complexity and stock assignment but, currently, there is not a consensus to which stock Slope Sea spawners should be assigned, or how this information may affect our understanding of stock structure (Walter et al., 2016). These results also suggest possible alternate spatial configurations, such as moving the split between areas 8 and 9 (Eastern Atlantic areas) to the Straits of Gibraltar.

Summarizing electronic tagging data movement parameters based on area of tagging is not analogous to stock assignment, but it does have the effect of functionally including movement patterns from a minority occurring stock within the majority stock within the variability of those parameters. For example, in our approach, western tagged fish behave similarly. Eastern origin fish that travel to the Med represent increased variability in the parameter estimates for months they are in the eastern Atlantic and Mediterranean. The number of Western tagged fish that crossed the 45o W line is low: 9/189 for fish \>=185cm (4.8%), 5/113 for fish \< 185 cm (4.4%).

An interesting and valuable exercise would be to approach the parameter summarization as described above, and assign a probability of switching parameter sets when moving into areas and during seasons where mixing is more likely to occur. This would have the biological effect of schools mixing and fish taking on the movement characteristics of other fish. This probability could be informed by the matrices reported here as well as from biological sampling (e.g. Rooker et al., 2014; Graves et al., 2015; Siskey et al., 2016).

Atlantic bluefin tuna are currently assessed using the VPA 2-box method (Porch, 2003), which is usually applied separately to the eastern and western stocks (ICCAT, 2014). The current benchmark assessment affords the opportunity to apply this method with mixing, and to compare results against other movement inclusive methods. One essential question as to the nature of the mixing between the two stocks is whether the two stocks represent an overlap model, where fish return to natal spawning grounds without deviation, or a diffusive model where fish, typically from the larger stock (eastern) more or less permanently emigrate and take on the characteristics of the western stock. The current application of SatTagSim more closely represents a diffusive method, but it could easily be extended to examine other scenarios.

Finally, future work may include use of additional tagging datasets to produce a more complete picture of telemetry based movement. These could include those from Stanford University, the Department of Fisheries and Oceans (Canada), The University of Cadiz (Aranda et al., 2013, Abascal et al., 2016), and Ifremer (Fromentin and Lopuszanski, 2013). Increased data will refine these simulations by providing a more robust analysis of bluefin migrations.

## Acknowledgements

We thank Dr. Tim Miller of the Northeast Fisheries Science Center, Dr. Lisa Kerr of the Gulf of Maine Research Institute, Dr. Geoff Cowles of the University of Massachusetts Dartmouth, and Dr. Chi Hin (Tim) Lam of University of Massachusetts, Boston, for valuable feedback, technical assistance and inspiration. This work was possible due to the NOAA/Seagrant Population Dynamics Fellowship (NA11OAR4170184) to B. Galuardi and a Bluefin Tuna Research Program grant (NA13NMF4720061) to M. Lutcavage. Special thanks to GBYP and tagging partners for tagging data: Fundacion AZTI, Instituto Espanol de Oceanografia, INRH, IZOR, COMBIOMA, Istanbul University, Universitat Politecnica de Valencia, Kali Tuna (Croatia) and the World Wildlife Fund.

This work was carried out under the provision of the ICCAT Atlantic Wide Research Programme for Bluefin Tuna (GBYP), funded by the European Union, by several ICCAT CPCs, the ICCAT Secretariat and by other entities (see: http://www.iccat.int/GBYP/en/Budget.htm). The contents of this paper do not necessarily reflect the point of view of ICCAT or of the other funders, which have not responsibility about them, neither do they necessarily reflect the views of the funders and in no ways anticipate the Commission’s future policy in this area.   References Abascal, F.J., Medina, A., De La Serna, J.M., Godoy, D., and Aranda, G. 2016. Tracking bluefin tuna reproductive migration into the Mediterranean Sea with electronic pop-up satellite archival tags using two tagging procedures. Fish. Oceanogr. 25(1): 54–66. doi:10.1111/fog.12134. Amante, C., and Eakins, B.W. 2009. ETOPO1 1 Arc-Minute Global Relief Model: Procedures, Data Sources and Analysis. NOAA Tech. Memo. NESDIS NGDC-24: 19–pp. Aranda, G., Abascal, F.J., Varela, J.L., and Medina, A. 2013. Spawning Behaviour and Post-Spawning Migration Patterns of Atlantic Bluefin Tuna (Thunnus thynnus) Ascertained from Satellite Archival Tags. PLoS ONE 8(10). doi:10.1371/journal.pone.0076445. Boyer, T.P., Antonov, J.I., Baranova, O.K., Garcia, H.E., Johnson, D.R., Mishonov, A.V., O’Brien, T.D., Seidov, D., Smolyar, I. (Igor), Zweng, M.M., Paver, C.R., Locarnini, R.A., Reagan, J.R., Coleman, C., and Grodsky, A. 2013. World ocean database 2013. doi:10.7289/V5NZ85MT. Carruthers, T., and Davies, C. 2014. Evaluating Management Strategies for Atlantic Bluefin Tuna. Available from http://www.iccat.int/GBYP/Documents/MODELLING/PHASE%205/MODELLING_PHASE5_CARRUTHERS_REPORT_1.pdf. Carruthers, T., Kimoto, A., Powers, J.E., Kell, L., Butterworth, D.S., Lauretta, M.V., and Kitakado, T. 2016a. Structure and estimation framework for Atlantic bluefin tuna operating models. Collect Vol Sci Pap ICCAT 72(7): 1782–1795.. Carruthers, T., Powers, J.E., Lauretta, M.V., Di Natale, A., and Kell, L. 2016b. A summary of data to inform operating models in management strategy evaluation of Atlantic bluefin tuna. ICCAT Collect. Vol. Sci. Pap. 72: 1796–1807.. Cermeño, P., Quílez-Badia, G., Ospina-Alvarez, A., Sainz-Trápaga, S., Boustany, A.M., Seitz, A.C., Tudela, S., and Block, B.A. 2015. Electronic Tagging of Atlantic Bluefin Tuna (Thunnus thynnus, L.) Reveals Habitat Use and Behaviors in the Mediterranean Sea. PLoS ONE 10(2). doi:10.1371/journal.pone.0116638. Fromentin, J.-M., and Lopuszanski, D. 2013. Migration, residency, and homing of bluefin tuna in the western Mediterranean Sea. ICES J. Mar. Sci. J. Cons. doi:10.1093/icesjms/fst157. Galuardi, B., Cadrin, S.X., Kerr, L., Miller, T.J., and Lutcavage, M. 2014. Using electronic tag data to provide transition matrices for Movement inclusive population models. ICCAT Col Vol Sci Pap 71(4): 1746–1756. Galuardi, B., and Chi Hin (Tim), L. 2014. Telemetry Analysis of Highly Migratory Species. In Stock Identification Methods: Applications in Fishery Science, 2nd edition. Edited by S.X. Cadrin, L.A. Kerr, and S. Mariani. Academic Press. pp. 447–476. Galuardi, B., and Lutcavage, M. 2012. Dispersal Routes and Habitat Utilization of Juvenile Atlantic Bluefin Tuna, Thunnus thynnus, Tracked with Mini PSAT and Archival Tags. PLoS ONE 7(5). doi:10.1371/journal.pone.0037829. Graves, J.E., Wozniak, A.S., Dickhut, R.M., Cochran, M.A., MacDonald, E.H., Bush, E., Arrizabalaga, H., Goñi, N., and MacLatchey, D. 2015. Transatlantic movements of juvenile Atlantic bluefin tuna inferred from analyses of organochlorine tracers. Can. J. Fish. Aquat. Sci.: 1–9. doi:10.1139/cjfas-2014-0305. ICCAT. 2014. Report of the 2014 Atlantic Bluefin Tuna Stock Assessment Session. ICCAT, Madrid, Spain. Kerr, L.A., Cadrin, S.X., and Secor, D.H. 2012. Evaluating population effects and management implications of mixing between Eastern and Western Atlantic bluefin tuna stocks. ICES CM (13). Available from http://www.ices.dk/sites/pub/CM%20Doccuments/CM-2012/N/N1312.pdf. Kerr, L.A., Cadrin, S.X., Secor, D.H., and Taylor, N.G. 2016. Modeling the implications of stock mixing and life history uncertainty of Atlantic bluefin tuna. Can. J. Fish. Aquat. Sci. doi:10.1139/cjfas-2016-0067. Lam, C.H., Nielsen, A., and Sibert, J.R. 2010a. Incorporating sea-surface temperature to the light-based geolocation model TrackIt. Mar. Ecol. Prog. Ser. 419: 71–84. doi:10.3354/meps08862. Lam, C.H., Nielsen, A., and Sibert, J.R. 2010b. Incorporating sea-surface temperature to the light-based geolocation model TrackIt. Mar. Ecol. Prog. Ser. 419: 71–84. doi:10.3354/meps08862. Neilson, J.D., Loefer, J., Prince, E.D., Royer, F., Calmettes, B., Gaspar, P., Lopez, R., and Andrushchenko, I. 2014. Seasonal Distributions and Migrations of Northwest Atlantic Swordfish: Inferences from Integration of Pop-Up Satellite Archival Tagging Studies. PLoS ONE 9(11). doi:10.1371/journal.pone.0112736. Porch, C.E. 2003. VPA-2BOX Version 3.01 User’s guide. Sustain. Fish. Div. Contrib. SFD-0102-151 NOAA Fisheries, Southeast Fisheries Science Center, 75 Virginia Beach Dr. Miami, Florida 33149 USA. R Core Team. 2015. R: A Language and Environment for Statistical Computing. R Foundation for Statistical Computing, Vienna, Austria. Available from http://www.R-project.org. Restrepo, V.R., Diaz, G.A., Walter, J.F., Neilson, J., Campana, S.E., and Secor, D. 2010. Updated Estimate of the Growth Curve of Western Atlantic Bluefin Tuna. Coll Vol Sci Pap SCRS/2009/160: 1–12. Richardson, D.E., Marancik, K.E., Guyon, J.R., Lutcavage, M.E., Galuardi, B., Lam, C.H., Walsh, H.J., Wildes, S., Yates, D.A., and Hare, J.A. 2016. Discovery of a spawning ground reveals diverse migration strategies in Atlantic bluefin tuna (Thunnus thynnus). Proc. Natl. Acad. Sci. 113(12): 3299–3304. doi:10.1073/pnas.1525636113. Rooker, J.R., Arrizabalaga, H., Fraile, I., Secor, D.H., Dettman, D.L., Abid, N., Addis, P., Deguara, S., Karakulak, F.S., Kimoto, A., Sakai, O., Macas, D., and Santos, M.N. 2014. Crossing the line: migratory and homing behaviors of Atlantic bluefin tuna. Mar. Ecol. Prog. Ser. 504: 265–276. doi:10.3354/meps10781. Sibert, J.R., Lutcavage, M.E., Nielsen, A., Brill, R.W., and Wilson, S.G. 2006. Interannual variation in large-scale movement of Atlantic bluefin tuna (Thunnus thynnus) determined from pop-up satellite archival tags. Can. J. Fish. Aquat. Sci. 63(10): 2154–2166. doi:10.1139/f06-114. Sibert, J.R., Musyl, M.K., and Brill, R.W. 2003. Horizontal movements of bigeye tuna near Hawaii from archival tagging data. Fish. Oceanogr. 12: 141–151. Siskey, M.R., Wilberg, M.J., Allman, R.J., Barnett, B.K., and Secor, D.H. 2016. Forty years of fishing: changes in age structure and stock mixing in northwestern Atlantic bluefin tuna (Thunnus thynnus) associated with size-selective and long-term exploitation. ICES J. Mar. Sci. J. Cons.: fsw115. doi:10.1093/icesjms/fsw115. Taylor, N.G., McAllister, M.K., Lawson, G.L., Carruthers, T., and Block, B.A. 2011. Atlantic Bluefin Tuna: A Novel Multistock Spatial Model for Assessing Population Biomass. PLoS ONE 6(12). doi:10.1371/journal.pone.0027693#s5. Teo, S.L.., Boustany, A., Blackwell, S., Walli, A., Weng, K.C., and Block, B.A. 2004. Validation of geolocation estimates based on light level and sea surface temperature from electronic tags. Mar. Ecol. Prog. Ser. 283: 81–98. Walter, J.F., Porch, C.E., Lauretta, M.V., Cass-Calay, S.L., and Brown, C.A. 2016. Implications of alternative spawning for bluefin tuna remain unclear. Proc. Natl. Acad. Sci.: 201605962. \[accessed 28 February 2017\]. Wilson, S.G., Jonsen, I.D., Schallert, R.J., Ganong, J.E., Castleton, M.R., Spares, A.D., Boustany, A.M., Stokesbury, M.J.W., and Block, B.A. 2015. Tracking the Fidelity of Atlantic Bluefin Tuna Released in Canadian Waters to the Gulf of Mexico Spawning Grounds. Can. J. Fish. Aquat. Sci. doi:10.1139/cjfas-2015-0110.

  Table 1. Datasets used in simulations.

Owner Primary Area of release Size at release Number of tags Years tagged Principal Investigator LPRC/UMass Boston Canadian Maritimes, Gulf of Maine 75-300 cm 302 1997-2014 Molly Lutcavage NOAA, SEFSC Gulf of Mexico 190-270 cm 31 2010-2012 Craig Brown AZTI Bay of Biscay 66-110 cm 20 2005-2010 Igor Arregi/Haritz Arrizabalaga GBYP Multiple; Eastern Atlantic and Med 56-265 cm 146 2011-2015 Antonio Di Natale Total Western 333\
Total Eastern 166\
Grand Total 499

Table 2. Parameters derived from 189 western tagged Atlantic bluefin \>= 185 cm CFL. Advective terms are u and v while D indicates diffusion. The ‘sd’ prefix indicates standard deviation. Units are nautical miles/day (nmd-1) for u, v, sd.u, sd.v, and nautical miles squared per day (nm2d-1) for D and sd.D.

Month u v D sd.u sd.v sd.D 1 2.14 -2.04 1221.28 12.30 8.07 1253.39 2 -1.24 -1.69 1304.15 18.18 7.93 1300.40 3 -2.27 0.61 1405.27 16.04 11.71 1337.40 4 2.03 5.70 1284.55 16.73 10.32 1299.74 5 9.26 1.07 1282.14 16.32 10.08 1386.94 6 13.60 17.15 1388.65 21.19 17.73 1470.72 7 1.23 4.27 1253.62 14.63 13.26 1449.20 8 0.57 -0.62 1053.34 4.55 5.36 1365.82 9 0.88 -0.22 1062.58 4.75 9.36 1315.52 10 -2.99 -7.69 1081.05 10.01 11.06 1178.61 11 -8.16 -9.05 1076.06 10.19 9.39 1135.88 12 -1.95 -2.10 1128.35 9.33 6.71 1165.03

  Table 3. Parameters derived from 113 western tagged Atlantic bluefin \< 185cm CFL. Terms and units follow those in Table 2.

Month u v D sd.u sd.v sd.D\
1 1.39 -1.92 961.81 10.96 8.38 1056.34 2 0.40 -0.88 945.05 13.18 6.28 1064.86 3 0.24 -0.14 955.22 12.75 9.40 1061.66 4 1.18 5.58 923.52 13.24 8.91 1043.36 5 0.76 2.37 943.17 11.61 6.38 1152.37 6 1.32 3.32 1085.69 15.72 10.75 1288.33 7 -0.32 1.22 981.51 10.74 7.47 1193.80 8 0.33 -0.53 848.29 3.42 4.76 1143.32 9 0.32 -1.08 903.56 4.44 6.53 1067.70 10 -2.42 -5.62 937.12 7.88 9.36 1000.87 11 -5.91 -7.21 947.13 10.26 10.01 997.11\
12 -1.19 -2.83 936.52 7.97 7.75 992.68

Table 4. Parameters derived from 166 eastern tagged Atlantic bluefin. Terms and units follow those in Table 2.

Month u v D sd.u sd.v sd.D 1 -0.89 -1.23 946.54 10.34 4.98 718.32 2 -1.23 -0.21 845.77 6.77 4.18 574.34 3 -0.77 -0.82 790.73 4.75 2.88 345.45 4 0.53 0.76 790.98 4.34 2.03 352.88 5 6.44 1.54 970.84 25.05 7.89 493.53 6 4.48 0.91 879.66 19.11 7.15 478.84 7 -8.81 4.01 915.88 15.46 11.16 514.00 8 -0.88 3.12 1010.16 5.17 8.06 572.07 9 -1.77 1.49 1017.43 6.88 8.07 757.13 10 0.17 -0.29 1027.69 7.05 6.01 724.73 11 -1.45 0.11 1037.25 5.69 4.07 699.24 12 -0.69 -0.71 1018.30 6.28 6.90 704.73

Figure 1. Electronic tagging data used in the analysis. Large Pelagics Research Center (LPRC) included fish both \>=185cm and \< 185cm and included both immature and mature individuals. The NOAA data were all mature fish, \>=185cm. AZTI data were mostly immature fish (Arregi at al., in prep). GBYP likely had a mix of mature and immature fish.

Figure 2. Cumulative distributions of tag measured temperatures from the LPRC electronic tagging data (n = 341 fish). Plots show the percentage of observations (y-axis) that fell with each temperature (x-axis). The mean (red line) and 95% quantiles (blue lines) are displayed for reference. The temperature range used for the simulations is less stringent than these observations to account for unobserved variance.

Figure 3. Two spatial stratification schemes considered for movement transitions. The 4-box model is an aggregated subset of the 11-box model. The 4-box model was adjusted slightly so that the western boundary did not cross into the Pacific Ocean.

Figure 4. Western tagged fish \>= 185 cm CFL, 4 box model. In each cell, the first line represents the mean transition probability from the previous season to the current season. The colorbar represents the mean as a visual aid. The second line in each cell is the 95% confidence interval of the 1000 replicate runs. Figures 5-9 are labeled in this manner.  

Figure 5. Western tagged fish \< 185 cm CFL, 4 box model.  

Figure 6. Eastern tagged fish, 4 box model.

Figure 7. Western tagged fish \>= 185 cm CFL, 11 box model

Figure 8. Western tagged fish \< 185 cm CFL, 11 box model.

Figure 9. Eastern tagged fish, 11 box model.  

Figure 10. Histogram of days at liberty for the combined NOAA and LPRC datasets (n = 333). This highlights the prevalence of relatively short tagging durations.
