---
title: New Outline for Chapter 3
subtitle: Atlantic Bluefin Tuna Area Transition Matrices Estimated From Electronic Tagging and SatTagSim
authors:
  - name: Benjamin Galuardi
    affiliation: School of Marine Science and Technology, University of Massachusetts Dartmouth, Fairhaven, MA, USA
    roles: writing, analysis
    corresponding: true
    email: benjamin.galuardi@noaa.gov
  - name: Steven X. Cadrin
    affiliation: School of Marine Science and Technology, University of Massachusetts Dartmouth, Fairhaven, MA, USA
    roles: writing
  - name: Igor Arregi
    affiliation: AZTI Technalia, Marine Research Division, Pasaia (Gipuzkoa), Spain
    roles: writing
  - name: Haritz Arrizabalaga
    affiliation: AZTI Technalia, Marine Research Division, Pasaia (Gipuzkoa), Spain 
    roles: data and analysis
  - name: Antonio DiNatale
    affiliation: ICCAT Secretariat, Madrid, Spain
    roles: data and analysis
  - name: Craig Brown
    affiliation: Southeast Fisheries Science Center, NOAA Fisheries, Miami, FL, USA
    roles: data and analysis
  - name: Matt Lauretta
    affiliation: Southeast Fisheries Science Center, NOAA Fisheries, Miami, FL, USA
    roles: data and analysis
  - name: Molly Lutcavage
    affiliation: Large Pelagics Research Center, Gloucester, MA, USA     
    roles: writing, data, and analysis
bibliography: references.bib
format:
  elsevier-pdf:
    journal:
      name: "Fisheries Research"
      formatting: preprint
      model: 5p
      layout: onecolumn
      cite-style: authoryear
      highlights:
    include-in-header: 
      text: |
        \newpageafter{author}
  html: default
  docx: default
  jats: default
  plos-pdf: default
---

# Summary

We demonstrate use of a telemetry based method for simulating individual based movements to produce transition matrices for movement inclusive models. A custom R package (SatTagSim) was used on Atlantic bluefin tuna electronic tagging data from the Large Pelagics Research Center (UMass Boston), AZTI Technalia, the Grande Bluefin Year Program, and the National Marine Fisheries Service (USA) to derive transition matrices for an 11-box and 4-box model. Migration rate matrices were produced for western Atlantic tagged fish \>185cm, and \<185 cm, as well as for eastern tagged fish (all sizes). The estimates provided are fishery independent and external to the operational and assessment frameworks. The results are highly informative to the assessment by (1) providing estimates of bluefin tuna movement for consideration as fixed values, prior probabilities on movement, or for direct comparison with estimates of movement from mixed stock assessment models (2) to facilitate discussion of movement rate assumptions and the use of electronic tagging data in various assessment models.

# Introduction

The benchmark assessment of Atlantic Bluefin tuna (*Thunnus thynnus*) in 2017 offers a unique opportunity to take advantage of the wealth of electronic tagging data collected in the past 20+ years. <!--# this is old news. this should be updated -->The Grande Bluefin Year Program (GBYP), a project within the International Commission for the Conservation of Atlantic Tunas (ICCAT), in particular offers a source of tagging data originating in the eastern Atlantic that was not previously available. Management strategy evaluation (MSE) is a priority for Atlantic bluefin tuna management and is currently a funded initiative within ICCAT [@carruthers2014]. Development of operating models is a key component to MSE and can be a vector for utilizing electronic tag data [@kerr2012a; @kerr2016; @carruthers2016]

There are several challenges in making these data usable in assessment activities. The first is to summarize the data in a way that is readily usable by models. Not all tagging data are equal in terms of length, area, and season of deployment. Fish are often tagged opportunistically, when and where they are accessible e.g. [@galuardi2012, @cermeño2015, @wilson2015]. Last, tagging data are expensive to collect and hold incredibly high scientific value. Allowing time for individual programs to publish results often means data are not quickly available for other purposes.

The solution to many of these issues is to simplify the manner in which the data are represented, and summarize it in an easily usable format. Empirical summaries by area and season offer the simplest method for incorporating many different data sources without compromising individuals information for other purposes [@carruthers2016a]. Simple summaries do not, however, take into account the uncertainties in the positions from which they were derived and do not deal effectively with the biases of short tracks in these datasets. A more robust method is to use individual based simulation, based on the tagging data, to produce movement probability metrics by season and area [@galuardi2014]. Here, we use several electronic tagging datasets, from the eastern and western Atlantic (Figure 1), to produce seasonal movement matrices for use in current and future operational and assessment models of Atlantic bluefin tuna. We use the 11-box model developed for the GBYP MSE [@carruthers2016a] as well as a simplified 4-box model. Simulation and matrix derivations were carried out using a custom package (SatTagSim) for the R statistical software [@rcoreteam2024].

## elements/sections

The best idea is to make the AFS 2017 talk into a chapter. It has all the elements it just need text. Basic textr can be used from the SCRS 2017 paper but the matrices, pieces, and interpretations are beyond what that paper offered.

-   update SCRS 2017 paper with figures/text from using 3D parameters

    -   This was already done for the AFS 2017 talk!!
    -   Use these figures: "C:\\Users\\ben\Google Drive\\PHD\\PUBS_TALKS\\AFS2017\\FIGS"
    -   Use this script! "C:\\Users\\ben\\Google Drive\\PHD\\COLLABORATIONS\\AFS_2017_figs_8-8-17.r"

How many tracks were used? 170 east, 220 west E/W size split? how many sims were done? how was variance derived?

-   Add E/W combination

    -   demonstrates sharing of movement parameters in the case of mixing

-   use $\chi^2$ goodness of fit to compare transitions between small/large fish

    -   multinomial variance

    -   use matrix variance example

-   use $\chi^2$ goodness of fit to compare transitions between E/W

## Chapter 2 notes

-   add visual of advection calculation
-   add method/demo of variance calculation
-   add method/demo of overall transition rate
-   add method/demo of comparison between two matrices
-   add functions to do comparisons
